### ISSUE TITLE
Failed thumbnails

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#994] opened 2016-07-22 16:15 UTC
Kevin emailed me this morning to let me know that one of his file uploads from yesterday is stuck in process: https://repository.library.northeastern.edu/files/neu:cj82nc047

It looks like it's not the file that stalled, but the thumbnail creation? It looks like there are 6 failed thumbnail jobs in resque.

**Comment by elizoller** [comment] 2016-07-22 16:19
The failed jobs in resque are from the set_thumbnail_creation_job which is for adding thumbnails to collections and communities.

**Comment by elizoller** [comment] 2016-07-22 16:21
I'll look into the thumbnail creation job error more. Do you know of anything wrong with this core_file (besides that it didn't get marked as completed)? Is it missing anything?

**Comment by sarahjeansweeney** [comment] 2016-07-22 16:25
Not that I can tell. This is all the info I have:

> I mistakenly uploaded the incorrect .jpeg to neu:cj82nc02p [see In vitro evaluations… below] and now the file is stalled in “Updating”. I need this file un-stuck so I can upload the correct .jpeg.

I've asked for more clarification.

**Comment by elizoller** [comment] 2016-07-22 16:43
Replacing the thumbnail through the Manage File tab works for me on production.

**Comment by dgcliff** [comment] 2016-07-25 13:44
I believe this, and the failed jobs

```It looks like there are 6 failed thumbnail jobs in resque.```

are related. Both occurred on a Thursday, and are highly unusual. It appears as though Cerberus was unable to communicate with Fedora for a period of time. Given the time of week, and our inability to recreate the issue, I'm going to put it down to a service interruption caused by an ITS update.

Unfortunately, if it was at the network level, there's very little we could've done to prevent it.

**Closed by dgcliff** 2016-07-25 13:44 UTC
Labels: bug
