### ISSUE TITLE
Tombstoning Procedure

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#620] opened 2014-12-08 20:43 UTC
From our discussion today about tombstoning:
There will be a difference between deleting an object and tombstoning in Cerberus: Deleting will remove the core file and all its associated objects. Tombstoning will suppress the files and full metadata from display, but the following information will display to all users:
* Custom explanatory note
* Title
* Creator(s)
* Handle

Tombstoned objects will not be discoverable through search, and for now only DRS staff can tombstone an object.

@dgcliff proposed that there should be a set list of states in Fedora:
* Deleted
* Tombstoned
* Embargoed
* Live

**Comment by elizoller** [comment] 2015-05-07 13:03
I think this is all set

**Comment by sarahjeansweeney** [comment] 2015-05-07 13:15
Is the display for tombstoned files in place? We want some metadata for tombstones to display (the explanatory note, the title, etc)., but when I click the handle for a tombstoned record now I just see the "Sorry the file you requested..." page (see: http://hdl.handle.net/2047/D20128877).

**Comment by elizoller** [comment] 2015-05-07 14:35
As far as I know we aren't storing the explanatory note besides just sending it in the email. So I'll reopen this.

**Comment by sarahjeansweeney** [comment] 2015-05-07 18:23
The justification users enter when they submit the request don't need to be saved. The explanatory note will be stock text I'll add when I tombstone the item ("Removed from view at Northeastern University’s discretion May 7, 2015", etc...). I suppose this would live in the properties datastream?

**Comment by dgcliff** [comment] 2015-05-08 14:11
If it's stock text regardless of the item, it should live in the yml file somewhere

**Comment by elizoller** [comment] 2015-09-18 18:44
@sarahjeansweeney  Do you want this to be stock text across all files?
Either way, we could do something like this:
<img width="1198" alt="screen shot 2015-09-18 at 2 41 36 pm" src="https://cloud.githubusercontent.com/assets/5439169/9967922/83cc3ab8-5e13-11e5-9a79-33afd3f7c5cf.png">

**Comment by sarahjeansweeney** [comment] 2015-09-18 20:20
To clarify: the stock text is less stock and more standard. I have three standard statements I'll use when tombstoning an item. That text should probably live with core file (properties, MODS, doesn't really matter) and display to the user.

**Comment by elizoller** [comment] 2015-09-18 20:46
If this is to be stored long term in mods, what would the mods look like?

**Comment by elizoller** [comment] 2015-09-23 13:14
@sarahjeansweeney MODS is probably the best place for this. How would this be written in MODS?

**Comment by sarahjeansweeney** [comment] 2015-09-23 13:53
accessCondition should be fine:
```
<mods:accessCondition type="restriction on access"></mods:accessCondition>
```

**Comment by elizoller** [comment] 2015-09-24 12:06
Can a MODS record contain multiple accessConditions? ie. a tombstoned marcom file that has a copyright statement + tombstoning reason

**Comment by dgcliff** [comment] 2015-09-24 12:36
Yep - the type changes though if I'm not mistaken

Restriction on access vs. use and reproduction

**Comment by elizoller** [comment] 2015-09-24 12:37
Ok thanks. Looking at the `insert_new_node` deal to add an accessCondition

**Comment by dgcliff** [comment] 2015-09-24 12:38
@elizoller ask Will if he's in - he wasn't fond of writing that I don't think. See if there's anywhere in mods_datastream that does something similar

**Comment by sarahjeansweeney** [comment] 2015-09-24 13:04
Those type values are suggested, and aren't controlled at all. We can definitely select our own type, and now that I think of it, we probably should choose something else, like type="suppressed"

**Comment by dgcliff** [comment] 2015-09-24 13:08
suppressed is great - reason: sedition to the drs developer :smile:

**Comment by elizoller** [comment] 2015-09-24 13:41
will is out today. i can get it to add the new node with the correct type but i'm unable to assign any value to it. it creates a self closing node like `<mods:accessCondition type="suppressed"/>`

**Comment by elizoller** [comment] 2015-09-28 14:22
@sarahjeansweeney what are the three standard statements?

**Comment by sarahjeansweeney** [comment] 2015-09-28 14:30
* Removed from view at Northeastern University’s discretion [date]
* Removed from view at Northeastern University Libraries’ discretion
[date]
* Removed from view by legal order [date]

**Comment by elizoller** [comment] 2015-09-28 14:30
Thanks

**Comment by elizoller** [comment] 2015-09-29 13:58
Fixed with https://github.com/NEU-Libraries/cerberus/pull/824

**Comment by elizoller** [comment] 2015-09-29 14:35
Feel free to check this out on staging. The tombstone reason will display if you go to a core file that has been tombstoned:
<img width="1213" alt="screen shot 2015-09-29 at 10 35 32 am" src="https://cloud.githubusercontent.com/assets/5439169/10167275/d62a252e-6695-11e5-943d-bc9bc7d51df6.png">

**Comment by elizoller** [comment] 2015-09-29 14:48
Going to change tombstoned objects to render a 410 ("gone") instead of 404 so the page can be customized more (no line about it never existed because we know it did exist) and less confusing.

**Comment by elizoller** [comment] 2015-09-29 15:19
<img width="1199" alt="screen shot 2015-09-29 at 11 19 03 am" src="https://cloud.githubusercontent.com/assets/5439169/10168696/eea89b7a-669b-11e5-93da-3d43973d14b2.png">

**Comment by sarahjeansweeney** [comment] 2015-09-29 17:29
@elizoller How customizable is this page? There are a few elements other than the note that should display (see the initial ticket: custom note, title, creator(s), and handle), and having both the yellow and asterisk notes seems redundant.

**Comment by elizoller** [comment] 2015-09-29 17:39
@sarahjeansweeney The yellow message is the actual stored tombstone file. we can customize this more.

**Comment by sarahjeansweeney** [comment] 2015-09-29 19:18
New text for 410 page:

"Title" was [reason] [date].

If you believe this item was removed in error, please contact DRS staff.

**Comment by elizoller** [comment] 2015-09-30 12:25
<img width="1215" alt="screen shot 2015-09-30 at 8 24 23 am" src="https://cloud.githubusercontent.com/assets/5439169/10192780/bf410b86-674c-11e5-85e5-5c628e26afdc.png">

**Comment by sarahjeansweeney** [comment] 2015-09-30 12:44
Looks good to me!

**Comment by sarahjeansweeney** [comment] 2015-10-05 20:01
Two more updates to the 410 page:
https://repository.library.northeastern.edu/files/neu:rx917b29x

* Can the page/tab title be changed from "DRS : System Error" to "DRS : File Removed"?
* I should have thought of this before, but if mods:title has a mods:nonSort field, the nonSort value should be included.

**Comment by elizoller** [comment] 2015-10-06 11:47
No problem. I'll patch that up.

**Closed** 2015-10-06 12:58 UTC
Labels: enhancement
