### ISSUE TITLE
Download queue creates .cpgz files instead of .zip files

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/cerberus#990] opened 2016-07-20 20:18 UTC
A user reported to me this afternoon that when she downloads files from her Download Queue, a .cpgz file is delivered instead of a .zip file, which she can't open ("It doesn’t do anything when I try to open the zip file other than create another zip-like file."):

![screen shot 2016-07-20 at 3 49 25 pm](https://cloud.githubusercontent.com/assets/4663073/17001512/48f246bc-4e95-11e6-948d-c8b75bdd6336.png)

I can't replicate this issue.

If it helps, she was experiencing this issue with this particular file: https://repository.library.northeastern.edu/files/neu:rx9162624
In this browser: Chrome for Mac Version 51.0.2704.103 (64-bit).

**Comment by dgcliff** [comment] 2016-07-20 20:28
Everything I've seen of this it seems to be

a) A common problem
b) An OSX/browser/zip utility problem

It appears we are doing what we're supposed to server side

**Comment by dgcliff** [comment] 2016-07-20 20:29
Going to close this, but will re-open if anyone can reproduce

**Comment by sarahjeansweeney** [comment] 2016-07-26 16:40
I was just able to reproduce this. I was downloading a bunch of my Sets to find examples for #996 and the last Set downloaded as `WrongCollection-.zip`, which when unzipped adds the .cpgz to the end (`WrongCollection-.zip.cpgz`). I'm not sure if this matters, but I've tried a few times and each time the file downloads with the "-" before the file extension. I downloaded 15-ish Sets, and this was the only one that was affected.

**Comment by dgcliff** [comment] 2016-07-26 16:41
Can you list the set pid?

**Comment by sarahjeansweeney** [comment] 2016-07-26 16:41
yup: https://repository.library.northeastern.edu/sets/neu:rx913q35n

**Comment by dgcliff** [comment] 2016-07-26 18:02
Fixable at least for some (perhaps all) of sets, relating to #996 

And we can at least do better error handling for the download queue

**Closed** 2016-08-09 17:05 UTC
